# Generated by Django 4.2.2 on 2023-11-06 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('published_date', models.DateField(auto_now_add=True)),
                ('image', models.ImageField(default='CeO.JPG', upload_to='images/')),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'db_table': 'blog_post',
            },
        ),
    ]
